### ISSUE TITLE
网盘失效了，可以在发一份吗

### ISSUE THREAD

**Issue by websecer** [nu0l/pwnwiki_backup#1]
网盘失效了，可以在发一份吗

**Comment by nu0l** [comment]
> 网盘失效了，可以在发一份吗

可以的，邮箱发我一下

**Comment by nu0l** [comment]
> 网盘失效了，可以在发一份吗

https://github.com/nu0l/pwnwiki_backup/releases/tag/1.0

**Comment by websecer** [comment]
感谢回复，我找到了一份
